"""empty message

Revision ID: 675ca13a6421
Revises:
Create Date: 2023-03-25 14:35:08.223386

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "675ca13a6421"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("web_hook_event_id", sa.String(length=255), nullable=True),
        sa.Column("reply_token", sa.String(length=255), nullable=True),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_message_id"), "events", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_message_type"), "events", ["message_type"], unique=False
    )
    op.create_index(op.f("ix_events_mode"), "events", ["mode"], unique=False)
    op.create_index(
        op.f("ix_events_reply_token"), "events", ["reply_token"], unique=False
    )
    op.create_index(
        op.f("ix_events_source_type"), "events", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_events_type"), "events", ["type"], unique=False)
    op.create_index(op.f("ix_events_user_id"), "events", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_events_web_hook_event_id"),
        "events",
        ["web_hook_event_id"],
        unique=False,
    )
    op.create_table(
        "reply_messages",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reply_messages_event_id"), "reply_messages", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reply_messages_event_id"), table_name="reply_messages")
    op.drop_table("reply_messages")
    op.drop_index(op.f("ix_events_web_hook_event_id"), table_name="events")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_index(op.f("ix_events_type"), table_name="events")
    op.drop_index(op.f("ix_events_source_type"), table_name="events")
    op.drop_index(op.f("ix_events_reply_token"), table_name="events")
    op.drop_index(op.f("ix_events_mode"), table_name="events")
    op.drop_index(op.f("ix_events_message_type"), table_name="events")
    op.drop_index(op.f("ix_events_message_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
